### PR TITLE
enhanced options handling

### PR DESCRIPTION
**Pull request by jamie-beck**
I have added the ability for the options to be restored from the original saved neural network or for new ones to be provided when restoring.

### CODE REVIEW

**Comment by jamie-beck** [comment]
Would you like me to change something about this pull request? Is there a problem?

**Comment by daffl** [comment]
Ah sorry about that. I like the options I'm not entirely sure about the `classifyTop` since it is not part of the original node-natural interface. Would you mind creating two separate pull requests?

**Comment by jamie-beck** [comment]
classifyTop is now gone.

**Comment by daffl** [comment]
Better late than never 😉 Thank you!

**Pull request merged**
